#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/update-homebrew-formula.sh [OPTIONS]

Regenerate the Homebrew formula for a maludb release using checksums in the
dist directory. Run after package-release.sh has produced the macOS and Linux
tarballs (and their .sha256 files) for the release.

Options:
  --version VERSION   Release version (without leading v). Defaults to Cargo.toml.
  --dist-dir DIR      Directory holding the .tar.gz.sha256 files. Defaults to dist.
  --output FILE       Formula path to write. Defaults to Formula/maludb.rb.
  --repo OWNER/NAME   GitHub repo for download URLs. Defaults to maludb/maludb-terminal.
  -h, --help          Show this help.
USAGE
}

cargo_version() {
  sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -n 1
}

version="$(cargo_version)"
dist_dir="dist"
output="Formula/maludb.rb"
repo="maludb/maludb-terminal"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --version) version="${2:?--version requires a value}"; shift 2 ;;
    --dist-dir) dist_dir="${2:?--dist-dir requires a value}"; shift 2 ;;
    --output) output="${2:?--output requires a value}"; shift 2 ;;
    --repo) repo="${2:?--repo requires a value}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "error: unknown option $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [ -z "$version" ]; then
  echo "error: could not determine version" >&2
  exit 1
fi

sha_for() {
  local target="$1"
  local file="$dist_dir/maludb-$version-$target.tar.gz.sha256"
  if [ ! -f "$file" ]; then
    echo "error: missing checksum file: $file" >&2
    exit 1
  fi
  awk 'NR==1 { print $1 }' "$file"
}

mac_arm="$(sha_for aarch64-apple-darwin)"
mac_intel="$(sha_for x86_64-apple-darwin)"
linux_arm="$(sha_for aarch64-unknown-linux-gnu)"
linux_intel="$(sha_for x86_64-unknown-linux-gnu)"

base="https://github.com/$repo/releases/download/v$version"

mkdir -p "$(dirname "$output")"
cat > "$output" <<RUBY
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh. Do not edit by hand.
class Maludb < Formula
  desc "Command-first CLI for sending notes, documents, and smoke tests to MaluDB"
  homepage "https://github.com/$repo"
  version "$version"

  on_macos do
    on_arm do
      url "$base/maludb-$version-aarch64-apple-darwin.tar.gz"
      sha256 "$mac_arm"
    end
    on_intel do
      url "$base/maludb-$version-x86_64-apple-darwin.tar.gz"
      sha256 "$mac_intel"
    end
  end

  on_linux do
    on_arm do
      url "$base/maludb-$version-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$base/maludb-$version-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_intel"
    end
  end

  def install
    bin.install "bin/maludb"
  end

  test do
    assert_match "maludb", shell_output("#{bin}/maludb --help")
  end
end
RUBY

echo "Wrote $output (maludb $version)"
